language: java
sudo: false
dist: trusty
jdk:
  - oraclejdk8
  - openjdk8
  - openjdk10
  - openjdk11

before_install:
- export TZ=Europe/Prague
- date
- wget http://ipinfo.io/ip -qO -

after_success:
- bash <(curl -s https://codecov.io/bash)

env:
  global:
  - GH_USERNAME: Travis-CI
  - GH_EMAIL: todvora@gmail.com
  - GH_REF: github.com/todvora/eet-client.git
  - secure: "DJc2EtFTwW5OmhL0HKo3ZLO7x2Gv+IGfpgf0LkabLrOkUyFGqiNSx158tZQkTLZuBGfe7lk5gZj3DMCFrIMHwr/LSTA0AioMc27zeIi3tsGYlGlIwB8njiipl/H41tf/lbmXV6J3FEIse95pzLJ4LWWy8E2Yv7J5WLrUO/FQcPmJCQgUOMaZ5JwHGHReMRdg2PpN3IyALdcdt258DyJF4Uln3lLnN+Xqtp1RYwxFZB4DzMbWQ2IzkY3pwBWZ6rQWML+tdxk3VmxKXeO2rpuAFJ4aqwn+EdZl7vv30NhU5YnFusY2kgFvT50EIHCc652KO/hodTZt91qXfwDUDcvQQd5zjwTFw3Z+B0Mbn09WUvB3rscycXB5UHURDHeS5C2pUQPPFVri/Ep6Gs+VDBaYmjsbdRv5MlCCWYG+YUFc7LckQ5bsRgpRiPyXSrwg2Je9jsp0cHxhUlTsStqwQ/E4iqhqTcYJgwM7Y10HvXQUPiFr2+zVpsiysdKKNQ9A2XP1RE2FwN9E1/+FHtcdFnbT8Sexjxokj72yF1D7wgXarFROPeEvzDiz09G5Do42Vvca1DPCGRjgDYLe0+xPLUfPS2JQODpeye6lIp7ulrKeIQwxkGON/97VsF88zyFnssvmoOBJ2WSbn7CwAIUEN2yvp8bttynGElc97SFer9kft9c="

deploy:
  - provider: releases
    api_key:
      secure: "gmPyRo7Ro639gPvcqnK6Dj8sdQZsjDy5XrEHC89q3JHuo0t+NAEfwtzN+GSC8FrGTAXjZm4C/8NkUXUqG+N4btK4Bdnhh58pc5s8ihQoKRKkEKEEu6iDkf8l9ety0AOvR7OkF2pVfQLu3v9y7Z66mNDy6P/Rjr6wLq0QSjBA3o7UvcOq+ilKENHLCIDNCp0BElyiVhDSDkZS1/2X1XIU8QgjRHzRoADEmKlejMss8sUm0Ol5qgZeLjVrPPdr+91mYsjSzEcpvUxY7Fo5ap2FU03V8+4BLGuHb+FTXNzLuwi6fp+9ufrapH5GR44ADPvHfv4ywp7Lug5lxlLVvXdi/QeLMY996EJapeaxmAdDE1Kwrz1ZwB0oT9sJB8kq3i14EffQ5BdG9fw2u0iy6qJpooSxLie1uI1SOa4ES1saltuFjP5Z3GsrylaOtazddqOdHTJYKcq27deQkJi9I8rSU7GiTuUgXqs2+WyH8g//Mc8+Kf8QPPW8xnmiBDusZixFsI2PwyeADFL0NCeICGRu5xup0f92kVqMJkYiPXwqBUJckF3F2M9YAz18CObuW8yy94UCz03NavzjXXU0t06KpSdvgkN4D3p0VtDVXsvc/qZybF0j3Z2Feb0oaLcltLnp+uy9+gNrpB+cgsvQmaaGY9n5FDrDiTaKJVgkazQoj+s="
    skip_cleanup: true
    file_glob: true
    file:
        - target/eet-client-*.*
    on:
        tags: true

  - provider: script
    script: scripts/deploy-pages.sh
    skip_cleanup: true
    on:
        tags: true
        jdk: oraclejdk8
