language: java
sudo: false
dist: trusty
jdk:
  - oraclejdk8
  - openjdk8
  - openjdk10
  - openjdk11

before_install:
- export TZ=Europe/Prague
- date
- wget http://ipinfo.io/ip -qO -

after_success:
- bash <(curl -s https://codecov.io/bash)

env:
  global:
  - GH_USERNAME: Travis-CI
  - GH_EMAIL: todvora@gmail.com
  - GH_REF: github.com/todvora/eet-client.git
  - secure: "DJc2EtFTwW5OmhL0HKo3ZLO7x2Gv+IGfpgf0LkabLrOkUyFGqiNSx158tZQkTLZuBGfe7lk5gZj3DMCFrIMHwr/LSTA0AioMc27zeIi3tsGYlGlIwB8njiipl/H41tf/lbmXV6J3FEIse95pzLJ4LWWy8E2Yv7J5WLrUO/FQcPmJCQgUOMaZ5JwHGHReMRdg2PpN3IyALdcdt258DyJF4Uln3lLnN+Xqtp1RYwxFZB4DzMbWQ2IzkY3pwBWZ6rQWML+tdxk3VmxKXeO2rpuAFJ4aqwn+EdZl7vv30NhU5YnFusY2kgFvT50EIHCc652KO/hodTZt91qXfwDUDcvQQd5zjwTFw3Z+B0Mbn09WUvB3rscycXB5UHURDHeS5C2pUQPPFVri/Ep6Gs+VDBaYmjsbdRv5MlCCWYG+YUFc7LckQ5bsRgpRiPyXSrwg2Je9jsp0cHxhUlTsStqwQ/E4iqhqTcYJgwM7Y10HvXQUPiFr2+zVpsiysdKKNQ9A2XP1RE2FwN9E1/+FHtcdFnbT8Sexjxokj72yF1D7wgXarFROPeEvzDiz09G5Do42Vvca1DPCGRjgDYLe0+xPLUfPS2JQODpeye6lIp7ulrKeIQwxkGON/97VsF88zyFnssvmoOBJ2WSbn7CwAIUEN2yvp8bttynGElc97SFer9kft9c="

deploy:
  - provider: releases
    api_key:
      secure: "QOhCScBt9We5yeIXraFAoJGXLFxnFUs2pfciuHmRyinuJgFGISWrBJj3eoRzSAQi5AoDlZht4vpIBLKasMhD1/u4/w0139hLAxIpIrqAGJi3xyhDD26MjIYCK0igTBziIv6qJc0zuNGaJKWeO22xVb6iLqZTjmOFW+p1Xx7DV1OLHXtxUqi/aBSFxehiEu4g6FTqto9PPkgCpXy5IoFmekzoxcQskw3GZGGVm1BoCv2DULLnbyKPhL2K9+66kFAoCuga115Y7XcPwg6w8edha/pICbcCI1WNrb2lwX1KX3/AWzWKkgo7qyGF15qas9RQwxGiA9eciYK0ZdnQFs4cwTd3XxfX+3MprdUL6rt/8qoQQemdLCgEDAtguj1P1qsFCsXOWlxJ+zotUJgHhSdH856xW+iOy1IV9dVg/RXxm2e6DwsG3g3gX6H07kwWXs+5GZBR3RzdSDtT1AT/uzuMvBIV6McGDLHTAcIgTzFezNeEUiOHZAODcJIPDIVI5Jr7/+XHf/kMshZ2R3wMseYcsRzr5FtEo1DY42weJpJSUVb3IoeEBCo6VAgk/VQDgrXXAA70VqvmLUV7i3gLcVYlwscpshMpSXFwohxyoP43YwhrVTztv0jWVM6flKQPRL1wj1QWrU4ldXsM8AI754FKeo5PSsswsbahAEf+P2uEb2M="
    skip_cleanup: true
    file_glob: true
    file:
        - target/eet-client-*.*
    on:
        tags: true

  - provider: script
    script: scripts/deploy-pages.sh
    skip_cleanup: true
    on:
        tags: true
        jdk: oraclejdk8
